### ISSUE TITLE
cn_tcm.dict.yaml 文件？

### ISSUE THREAD

**Issue by snake-git** [whitewatercn/rime_clinic#5]
项目介绍中有“cn_tcm.dict.yaml”， 但是在正式列表中似乎没有这个文件？

**Comment by whitewatercn** [comment]
感谢指正，已经修改，现在文件多比较混乱，之后我有空了规范一下
https://github.com/whitewatercn/rime_clinic/commit/133f716e0eea250f5c60c5d137d70cc401454935

**Comment by whitewatercn** [comment]
已经调整了文件位置，重新制作了介绍
现在应该直观多了
https://github.com/whitewatercn/rime_clinic/commit/15c80ccf278636503a8d9cd3c655d818cd685381
